create table hotels (  
    hotel_id number generated by default on null as identity primary key,  
    hotel_name varchar(250),  
    rating number
);

insert into hotels(hotel_name, rating) values ('hotel 1', 5);
insert into hotels(hotel_name, rating) values ('hotel 2', 3);
insert into hotels(hotel_name, rating) values ('hotel 3', 4);
insert into hotels(hotel_name, rating) values ('hotel 4', 3);
insert into hotels(hotel_name, rating) values ('hotel 5', 3);
insert into hotels(hotel_name, rating) values ('hotel 6', 4);
insert into hotels(hotel_name, rating) values ('hotel 7', 4);
insert into hotels(hotel_name, rating) values ('hotel 8', 4);

create table room_types (  
    room_type_id number generated by default on null as identity primary key,
    capacity number,
    comfort varchar(250)
);

insert into room_types(capacity, comfort) values (1, 'standard');
insert into room_types(capacity, comfort) values (2, 'standard');
insert into room_types(capacity, comfort) values (3, 'standard');
insert into room_types(capacity, comfort) values (1, 'premium');
insert into room_types(capacity, comfort) values (2, 'premium');
insert into room_types(capacity, comfort) values (3, 'premium');

select * from room_types;

select * from hotels;

create table rooms (  
    room_id number generated by default on null as identity primary key,  
    hotel_id number,
    room_type_id number,
    room_number number,
    price number,
    constraint fk_rooms_hotel_id foreign key (hotel_id) references hotels (hotel_id),
    constraint fk_rooms_room_type_id foreign key (room_type_id) references room_types(room_type_id)  
);

insert into rooms(hotel_id, room_type_id, room_number, price) values (1, 2, 1, 50);
insert into rooms(hotel_id, room_type_id, room_number, price) values (1, 3, 2, 70);
insert into rooms(hotel_id, room_type_id, room_number, price) values (1, 6, 3, 80);
insert into rooms(hotel_id, room_type_id, room_number, price) values (1, 4, 4, 100);

insert into rooms(hotel_id, room_type_id, room_number, price) values (2, 2, 1, 150);
insert into rooms(hotel_id, room_type_id, room_number, price) values (2, 6, 2, 170);
insert into rooms(hotel_id, room_type_id, room_number, price) values (2, 3, 3, 180);
insert into rooms(hotel_id, room_type_id, room_number, price) values (2, 4, 4, 190);

insert into rooms(hotel_id, room_type_id, room_number, price) values (3, 4, 1, 50);
insert into rooms(hotel_id, room_type_id, room_number, price) values (3, 3, 2, 70);
insert into rooms(hotel_id, room_type_id, room_number, price) values (3, 1, 3, 80);
insert into rooms(hotel_id, room_type_id, room_number, price) values (3, 2, 4, 90);

insert into rooms(hotel_id, room_type_id, room_number, price) values (4, 2, 1, 50);
insert into rooms(hotel_id, room_type_id, room_number, price) values (4, 3, 2, 70);
insert into rooms(hotel_id, room_type_id, room_number, price) values (4, 3, 3, 80);
insert into rooms(hotel_id, room_type_id, room_number, price) values (4, 2, 4, 100);

insert into rooms(hotel_id, room_type_id, room_number, price) values (5, 2, 1, 150);
insert into rooms(hotel_id, room_type_id, room_number, price) values (5, 3, 2, 170);
insert into rooms(hotel_id, room_type_id, room_number, price) values (5, 3, 3, 180);
insert into rooms(hotel_id, room_type_id, room_number, price) values (5, 2, 4, 190);

insert into rooms(hotel_id, room_type_id, room_number, price) values (6, 2, 1, 50);
insert into rooms(hotel_id, room_type_id, room_number, price) values (6, 3, 2, 70);
insert into rooms(hotel_id, room_type_id, room_number, price) values (6, 3, 3, 80);
insert into rooms(hotel_id, room_type_id, room_number, price) values (6, 2, 4, 90);

insert into rooms(hotel_id, room_type_id, room_number, price) values (7, 2, 1, 150);
insert into rooms(hotel_id, room_type_id, room_number, price) values (7, 3, 2, 170);
insert into rooms(hotel_id, room_type_id, room_number, price) values (7, 3, 3, 180);
insert into rooms(hotel_id, room_type_id, room_number, price) values (7, 2, 4, 190);

insert into rooms(hotel_id, room_type_id, room_number, price) values (8, 2, 1, 50);
insert into rooms(hotel_id, room_type_id, room_number, price) values (8, 3, 2, 70);
insert into rooms(hotel_id, room_type_id, room_number, price) values (8, 3, 3, 80);
insert into rooms(hotel_id, room_type_id, room_number, price) values (8, 2, 4, 90);

select * from rooms;

create table app_users (  
    user_id number generated by default on null as identity primary key,
    email varchar(250)
);

insert into app_users(email) values ('email1@domain.com');
insert into app_users(email) values ('email2@domain.com');
insert into app_users(email) values ('email3@domain.com');
insert into app_users(email) values ('email4@domain.com');
insert into app_users(email) values ('email5@domain.com');

select * from app_users;

create table discounts (  
    discount_id number generated by default on null as identity primary key,
    value number
);

insert into discounts(value) values (0);
insert into discounts(value) values (10);
insert into discounts(value) values (20);
insert into discounts(value) values (30);

select * from discounts;

create table bookings (  
    booking_id number generated by default on null as identity primary key,  
    room_id number,
    user_id number,
    discount_id number default 1,
    beginDate date,
    endDate date,
    constraint fk_bookings_room_id foreign key (room_id) references rooms (room_id), 
    constraint fk_bookings_user_id foreign key (user_id) references app_users (user_id),  
    constraint fk_bookings_discount_id foreign key (discount_id) references discounts (discount_id)  
);

insert into bookings(room_id, user_id, beginDate, endDate) values (5, 5, to_date('12-07-2013', 'dd-mm-yyyy'), to_date('17-07-2013', 'dd-mm-yyyy'));
insert into bookings(room_id, user_id, beginDate, endDate) values (2, 3, to_date('21-08-2014', 'dd-mm-yyyy'), to_date('28-08-2014', 'dd-mm-yyyy'));
insert into bookings(room_id, user_id, beginDate, endDate) values (7, 2, to_date('11-05-2015', 'dd-mm-yyyy'), to_date('17-05-2015', 'dd-mm-yyyy'));
insert into bookings(room_id, user_id, beginDate, endDate) values (8, 4, to_date('24-09-2017', 'dd-mm-yyyy'), to_date('28-09-2017', 'dd-mm-yyyy'));
insert into bookings(room_id, user_id, beginDate, endDate) values (2, 3, to_date('01-06-2016', 'dd-mm-yyyy'), to_date('07-06-2016', 'dd-mm-yyyy'));
insert into bookings(room_id, user_id, beginDate, endDate) values (1, 1, to_date('01-07-2018', 'dd-mm-yyyy'), to_date('07-07-2018', 'dd-mm-yyyy'));
insert into bookings(room_id, user_id, beginDate, endDate) values (2, 3, to_date('21-08-2019', 'dd-mm-yyyy'), to_date('28-08-2019', 'dd-mm-yyyy'));
insert into bookings(room_id, user_id, beginDate, endDate) values (1, 1, to_date('10-07-2020', 'dd-mm-yyyy'), to_date('17-07-2020', 'dd-mm-yyyy'));
insert into bookings(room_id, user_id, beginDate, endDate) values (20, 5, to_date('21-05-2020', 'dd-mm-yyyy'), to_date('28-05-2020', 'dd-mm-yyyy'));
insert into bookings(room_id, user_id, beginDate, endDate) values (8, 5, to_date('21-08-2020', 'dd-mm-yyyy'), to_date('28-08-2020', 'dd-mm-yyyy'));

select * from bookings;

create table sights (  
    sight_id number generated by default on null as identity primary key,  
    sight_name varchar(250),
    address varchar(250) 
);

insert into sights(sight_name, address) values ('sight 1', 'address 122');
insert into sights(sight_name, address) values ('sight 2', 'address 222');
insert into sights(sight_name, address) values ('sight 3', 'address 322');
insert into sights(sight_name, address) values ('sight 4', 'address 422');
insert into sights(sight_name, address) values ('sight 5', 'address 522');
insert into sights(sight_name, address) values ('sight 6', 'address 172');
insert into sights(sight_name, address) values ('sight 7', 'address 272');
insert into sights(sight_name, address) values ('sight 8', 'address 722');
insert into sights(sight_name, address) values ('sight 9', 'address 822');

select * from sights;

create table nearby_sights (
    hotel_id number,
    sight_id number,
    constraint fk_nearby_sights_hotel_id foreign key (sight_id) references hotels (hotel_id), 
    constraint fk_nearby_sights_sight_id foreign key (hotel_id) references sights (sight_id)   
);

insert into nearby_sights(hotel_id, sight_id) values (1, 1);
insert into nearby_sights(hotel_id, sight_id) values (1, 2);
insert into nearby_sights(hotel_id, sight_id) values (2, 1);
insert into nearby_sights(hotel_id, sight_id) values (3, 4);
insert into nearby_sights(hotel_id, sight_id) values (3, 5);
insert into nearby_sights(hotel_id, sight_id) values (3, 6);
insert into nearby_sights(hotel_id, sight_id) values (4, 6);
insert into nearby_sights(hotel_id, sight_id) values (4, 1);
insert into nearby_sights(hotel_id, sight_id) values (5, 1);
insert into nearby_sights(hotel_id, sight_id) values (5, 5);
insert into nearby_sights(hotel_id, sight_id) values (6, 1);
insert into nearby_sights(hotel_id, sight_id) values (6, 2);
insert into nearby_sights(hotel_id, sight_id) values (7, 1);
insert into nearby_sights(hotel_id, sight_id) values (7, 1);
insert into nearby_sights(hotel_id, sight_id) values (8, 1);
insert into nearby_sights(hotel_id, sight_id) values (8, 7);
insert into nearby_sights(hotel_id, sight_id) values (8, 8);

select * from nearby_sights;